feat(KEYP-397): build the PC/SC plugin
eclipse/keyple-java-plugin-pcsc pull request #1
Opened 2021-03-18 17:03 UTC by jeanpierrefortune

2021-03-19 13:58 UTC, andrei-cristea requested changes

2021-03-19 13:58 UTC, andrei-cristea commented on src/main/java/org/eclipse/keyple/plugin/pcsc/PcscPluginAdapter.java
> +  protected CardTerminals getCardTerminals() {
pourquoi protected ?

2021-03-19 16:52 UTC, jeanpierrefortune commented on src/main/java/org/eclipse/keyple/plugin/pcsc/AbstractPcscPluginAdapter.java
> +        logger.trace("{}: no contact reader identification filter set", getName());
oui, elle est par défaut si on n'a pas appelé le setter du builder.
Mais on vérifie non null dans le setter.
C'est ce qui permet de donner ou pas une règle d'identification. Si on n'en donne pas, c'est la méthode setContactless du reader qui doit être utilisée.

2021-03-19 16:53 UTC, jeanpierrefortune commented on src/main/java/org/eclipse/keyple/plugin/pcsc/AbstractPcscPluginAdapter.java
> +   * @param contactlessReaderIdentificationFilter null if the regex based filter is not set.
idem

2021-03-19 17:00 UTC, jeanpierrefortune commented on src/main/java/org/eclipse/keyple/plugin/pcsc/AbstractPcscPluginAdapter.java
> +    if (protocolRulesMap != null) {
C'est lié au fait que putAll lève une exception si l'argument est null.

2021-03-19 17:22 UTC, jeanpierrefortune commented on src/main/java/org/eclipse/keyple/plugin/pcsc/AbstractPcscReaderAdapter.java
> +   * <p>The default value is {@code EXCLUSIVE}.
Pas de solution avec @value, j'ai utilisé @link SharingMode#EXCLUSIVE

2021-03-19 17:31 UTC, jeanpierrefortune commented on src/main/java/org/eclipse/keyple/plugin/pcsc/PcscPluginAdapter.java
> +  protected CardTerminals getCardTerminals() {
vestige du passé

2021-03-23 08:49 UTC, andrei-cristea approved these changes

2021-03-23 08:56 UTC, merged